### ISSUE TITLE
Team-Einteilung abschließen

### ISSUE THREAD

**Issue by harrydehix** [STAMACODING/RSA-App#10]
Ich bin dafür, dass wir langsam die Team Abteilung abschließen. Zumindest so zeitnah, dass wir nächstes Wochenende (ab 30. April) beginnen können, zu coden🥳.

**Comment by rHedBull** [comment]
Ja, wenn nicht sogar schon früher wir haben jetzt ja nur jeden 2. Tag Schule

**Comment by harrydehix** [comment]
Alle haben sich in die Teams eingetragen🎊
