### ISSUE TITLE
Welche Schnittstelle zwischen Server und Client verwenden wir?

### ISSUE THREAD

**Issue by harrydehix** [STAMACODING/RSA-App#11]
Das Java-Framework bietet gewiss unterschiedliche Möglichkeiten, eine Verbindung zwischen einem Server und einem Client einzurichten. Wir sollten schauen, welche verschiedenen Möglichkeiten es gibt, bzw. welche Möglichkeit für unsere Zwecke am besten passt.

**Comment by rHedBull** [comment]
Was genau meinst du mit schnittstelle?

**Comment by harrydehix** [comment]
Kommt gleich, ich update die neu erstellsten Issues gleich. Die gehören alle zum Server-Projekt (unter STAMACODING -> Teams -> Server-Team -> Projects) auffindbar.
