### ISSUE TITLE
Gruppen- oder Einzelchats?

### ISSUE THREAD

**Issue by harrydehix** [STAMACODING/RSA-App#12]
Soll eine Kommunikation zwischen mehreren Clients möglich sein (Gruppenfunktionalität)? Oder reicht eine Client zu Client (Einzelchat) Übertragung?

**Comment by rHedBull** [comment]
Lass erst mal versuchen Einzelchats hinzubekommen oder?

**Comment by harrydehix** [comment]
Einzelchats
