### ISSUE TITLE
Was übertragen wir von Client über Server zu Client?

### ISSUE THREAD

**Issue by harrydehix** [STAMACODING/RSA-App#13]
Was für Daten müssen übertragen werden? Verwenden wir Strings oder lieber doch Byte-Packete?

**Comment by rHedBull** [comment]
bytes oder ? dann kann man theoretisch auch mal was anderes als Strings übertragen

**Comment by harrydehix** [comment]
Wäre ich auch dafür. Aber lass diese Fragen erst klären, wenn sich alle in die Teams eingetragen haben und wir vielleicht nochmal alle darüber gesprochen haben. Damit auch alle im Team damit einverstanden sind.

**Comment by harrydehix** [comment]
Bytes
