### ISSUE TITLE
Log Interface für andere Teams

### ISSUE THREAD

**Issue by harrydehix** [STAMACODING/RSA-App#15]
Könnte das Log-Team bitte ein **Java Interface** bereitstellen, dass die Funktion(en) enthält, die für das Loggen notwendig ist/sind. 

Dann könnten die anderen Teams schon jetzt Log-Statements einbauen (auch wenn diese noch nicht funktionsfähig wären, wäre es _praktisch_ sie einbauen zu können). Falls ihr nicht wisst, wie man Interfaces erstellt, bin ich gern die helfende Hand :D

**Comment by MrTK-Dev** [comment]
Es soll doch bitte jemand ein Projekt in Eclipse erstellen und hier commiten, danke!

**Comment by harrydehix** [comment]
Muss heute Geschi lernen😳. Bin ziemlich spät dran😂 Fürs Coden hab ich also daher erstmal keine Zeit💩

**Comment by MrTK-Dev** [comment]
closed in 31aa28d
