### ISSUE TITLE
please review and tell me where I am wrong or how useful this is for our server connections

### ISSUE THREAD

**Issue by rHedBull** [STAMACODING/RSA-App#18]
# sth isn't working as it should, maybe the bug is only on my device, for more info look into the TestServer and TestClient classes!!

**Comment by harrydehix** [comment]
Schaue mal

**Comment by harrydehix** [comment]
Hendrik kannst du mal in den Sprachchat kommen? (discord -> salty coder -> server -> serverraum)

**Comment by harrydehix** [comment]
Ein Semicolon hat gefehlt und Server und Client müssen den selben Port verwenden :D
