### ISSUE TITLE
Additionally letter in log files

### ISSUE THREAD

**Issue by MrTK-Dev** [STAMACODING/RSA-App#31]
**Describe the bug**
The Logger adds one additionally letter to the first line of the starting message to files.

**To Reproduce**
1. start the application
2. produce a log
3. ...
4. Profit!

**Expected behavior**
The starting message should stay the way it is saved as a string in the class.

**Screenshots**
no.

**Comment by harrydehix** [comment]
Closed in f7ddd20eec589dad48b1fb4bfbdaed3f26631646 (neues Log-System)
