### ISSUE TITLE
Change the quantity of .jar creation

### ISSUE THREAD

**Issue by MrTK-Dev** [STAMACODING/RSA-App#42]
**Describe the bug**
Es wäre wahrscheinlich sinnvoller, wenn der Maven-Bot nicht bei jedem Commit die Jars erstellen würde.

**Idea**
Gegebenenfalls könnte man Commits einen Identifikator hinzufügen, wenn die Jars erneuert werden sollten.

**Comment by harrydehix** [comment]
Simplere Alternative: onrelease statt onpush
