### ISSUE TITLE
Log filtern

### ISSUE THREAD

**Issue by harrydehix** [STAMACODING/RSA-App#43]
Wozu hat man Log-Levels, wenn man den Log nicht wirklich filtern kann?

Toll wäre es doch, wenn man in irgendeiner Form speichern könnte, welche Log-Levels in den Log-Dateien gespeichert und welche in der Konsole ausgegeben werden.

Vielleicht über so etwas wie `Logger.setLevels(LogType fileLogType, LogType consoleLogType)`. Aber das 'Wie?' wäre natürlich eure Sache :D Das angegebene Level wäre dann das "niedrigste Level", das ausgegeben wird.

**Comment by BeneCodecademy** [comment]
Eine Idee von uns war am Anfang, wenn wir das grundsätzliche Log-File fertig haben, verschiedene Log-Files für die verschiedenen Types zu machen.

**Comment by harrydehix** [comment]
Closed in f7ddd20eec589dad48b1fb4bfbdaed3f26631646
