### ISSUE TITLE
Neues Log Level hinzufügen oder vielleicht noch mehr?

### ISSUE THREAD

**Issue by harrydehix** [STAMACODING/RSA-App#44]
Im Moment haben wir folgende Log Levels:

1. Error
2. Warning
3. Debug
4. Test

Würde mir noch ein Log-Level wünschen, was eine höhere Priorität als Debug hat, aber eine niedrigere als Warning. Also so:

1. Error
2. Warning
3. _Info_
4. Debug
5. Test

Als ich nach einem Namen für das neue Log Level gesucht habe, bin im Internet auch auf Standards für Log-Systeme gestoßen, die von Firmen genutzt werden und bin da auf [das](https://www.ibm.com/support/knowledgecenter/en/SSEP7J_10.2.2/com.ibm.swg.ba.cognos.ug_rtm_wb.10.2.2.doc/c_n30e74.html) gestoßen.
Mir persönlich würde das System von IBM **deutlich mehr** gefallen, da es **mächtiger** ist. Man kann die Logs semantisch mehr nach ihrer Wichtigkeit ordnen. Auch gefällt mir die Unterscheidung zwischen "Fatal" und "Error". Denn manchmal treten eben Fehler auf, die man abfangen kann, manchmal führen Fehler aber auch zwanghaft zum Programmabsturz. Auch die Einteilung der Debug-Stufen ist top. Denn viele Logs sind nur fürs Debuggen da, manche davon jedoch nur für die "Detaillprogrammierung", manche für das grobe Ganze wichtig. So kann man, wenn man eine Funktion zum Filtern der Logs hat (siehe [hier](https://github.com/STAMACODING/RSA-App/issues/43#issue-694748507)), den Log viel besser nachvollziehen.

1. Fatal 
   - Logger.fatal(String class, String additionalMessage, Exception e) (Exception e als variables Argument)
   - führt immer zum Absturz 
   - Konsole: e.printStrackTrace() und dann System.exit(-1)
   - Datei: getStackTrace(e)* und nach dem Schreiben in die Datei System.exit(-1)
2. Error 
   - Logger.error(String class, String additionalMessage, Exception e) (Exception e als variables Argument)
   - führt nie zum Absturz 
   - Konsole: nur e.printStrackTrace()
   - Datei: nur getStackTrace(e)*
3. Warn
   - Logger.warn(String class, String message)
4. Info 
   - Logger.info(String class, String message)
5. Debug - Low 
   - Logger.debugLow(String class, String message)
6. Debug - Medium
   - Logger.debugMedium(String class, String message)
7. Debug - High
   - Logger.debugHigh(String class, String message)

Falls ihr findet, dass die Funktionsnamen zu lang sind, würde ja auch f, e, w, i, dL, dM und dH als Abkürzung reichen, aber das wäre eure Sache. Würde aber eh erstmal eure Meinung zum Vorschlag hören^^.

*Diese Funktion ist cool, weil damit der StackTrace eines Fehlers als String abfangbar ist. So kann man ihn auch ganz leicht in die Log-Dateien schreiben:
```java
public static String getStackTrace(final Throwable throwable) {
    final StringWriter sw = new StringWriter();
    final PrintWriter pw = new PrintWriter(sw, true);
    throwable.printStackTrace(pw);
    return sw.getBuffer().toString();
}

(...)
String s = getStackTrace(e);
(...)
```

**Comment by MrTK-Dev** [comment]
Jo, wenn ich das FileSystem nochmal überarbeite, können wir die gewünschten Features relativ simpel implementieren.

**Comment by harrydehix** [comment]
Perfectissimo!

**Comment by harrydehix** [comment]
Closed in f7ddd20eec589dad48b1fb4bfbdaed3f26631646
