### ISSUE TITLE
Wiki einrichten

### ISSUE THREAD

**Issue by harrydehix** [STAMACODING/RSA-App#5]
Da wir nun das Repository public gemacht haben, können wir nun ein Wiki einrichten, das zur Dokumentation des ganzen Projekts dient.

**Comment by BeneCodecademy** [comment]
Eine weitere Frage ist die Konvention. Wann und für welche Funktionen, Docs etc. brauchen wir eine neue Wiki-Page und wie soll diese aussehen. Außerdem sollte noch die Reihenfolge und eventuelle Ordnung nach Teams oder Wichtigkeit besprochen werden

**Comment by harrydehix** [comment]
Wiki ist eigentlich fertig eingerichtet. Ihr müsst nur noch eure Funktionen dokumentieren ;)
