### ISSUE TITLE
Brauchen wir Github-Pages?

### ISSUE THREAD

**Issue by harrydehix** [STAMACODING/RSA-App#6]
https://pages.github.com/

**Comment by MrTK-Dev** [comment]
Die Frage sollte lauten: "Was könnten wir mit der Möglichkeit, eine Seite hosten zu lassen, anstellen?"
Eine Möglichkeit wäre, die Dokumentation darüber zu hosten. Entweder für den Nutzer oder einem Developer.
Evtl auch irgendwelche Live-Daten oder ähnliches.
Das ganze hätte auf jeden Fall low Priority

**Comment by harrydehix** [comment]
Mir ist klar, dass man vieles cooles Zeugs damit anstellen kann. Befürchte nur, dass wir uns zu sehr in solchen Features verzetteln und dabei das eigentliche Projekt vernachlässigen. Ich stehe eher für "Keep it simple.". Also alles was nicht notwendig ist, erst einmal wegzulassen.

**Comment by harrydehix** [comment]
Die Dokumentation wäre doch schon über das integrierte Wiki für uns gehostet, oder nicht?

**Comment by rHedBull** [comment]
wen ich das richtig verstehe würde mit pages, dann doch auch dein (@harrydehix ) Rasberry Pie nicht mehr benötigt werden, da wir ja dann alles auf pages hosten so lange wir nicht zuviel RAM brauchen oder?

**Comment by harrydehix** [comment]
Github Pages bietet uns doch glaube ich nicht einen Server an, den wir zur Übertragung von Nachrichten nutzen können, sondern dient nur zur Darstellung des Projekts.
> Die GitHub-Pages ersetzen natürlich keine echtes Fullstack-Hosting. PHP, Node.js, Ruby, Pearl und sonstige serverseitige Programmiersprachen, die zuvor von einem Sever aufgeführt werden müssen, funktionieren natürlich nicht. GitHub-Pages liefert ausschließlich die Seiten aus und interpretiert diese nicht. Damit können wir tendenziell nur mit HTML, CSS und Javascript arbeiten.
Das Ziel von GitHub-Pages ist es auch nicht, Hosting-Unternehmen Konkurrenz zu machen, sondern ausschließlich feine und kleine Projektseiten, passend zu dem Repository, bereitzustellen. Mit der kostenlosen Nutzungsmöglichkeit von https:// erfüllt es diese Aufgabe sehr gut.
[Quelle: t3n](https://t3n.de/news/github-pages-719396/)

**Comment by rHedBull** [comment]
ok, ich weiß nicht ob wir es unbedingt brauchen, wäre aber auch kein Nachteil. Ich finde es wichtiger, dass wir mal von die ganze Orga abschließen und irgendwas funktionierendes coden

**Comment by harrydehix** [comment]
Der Meinung bin ich auch.

**Comment by MrTK-Dev** [comment]
Könnten wir nicht die HTML Datei von Javadocs damit hosten?

**Comment by harrydehix** [comment]
Wäre cool, wenn. Da müsste sich jemand aber informieren.

**Comment by harrydehix** [comment]
Hab mal eine Basic Seite erstellt.
