### ISSUE TITLE
Konventionen an die Macht

### ISSUE THREAD

**Issue by harrydehix** [STAMACODING/RSA-App#8]
Wir sollten uns auf bestimmte Konventionen einigen:

- Wie benennen wir Dateien?
- Welche Sprache (Deutsch, Englisch) verwenden wir für unser Projekt?
  - Dokumentatieren wir alles in Englisch?
  - Benennen wir Funktionen in Java etc. auf Englisch?
  - (...)
- (...)

Ich schlage vor, die festgelegten Konventionen in einer Datei festzuhalten.

**Comment by MrTK-Dev** [comment]
Alles auf Englisch, weil man das meist so macht. Für mich ist Deutsch schwerer lol

**Comment by harrydehix** [comment]
Auch Issues? Auch die Protokolle? Auch Kommentare wie diese hier?

**Comment by MrTK-Dev** [comment]
# Mein Vorschlag

## Deutsch

Issues, Projekte, Protokolle
--> überall da, wo wir direkt miteinander kommunizieren

## Englisch

Code (Funktionen, Klassen, etc.), WIKI, Applikation, Logs, etc.
--> überall da, wo der Nutzer drauf zugreifen und im Code selbst

## Translating

Man könnte dann zB verschiedene Spracheinstellungen für die Applikation bereitstellen.

**Comment by harrydehix** [comment]
Stimme ich mit überein. Frage mich nur, in welche Kategorie jetzt der Changelog, die README.md und der Ordner "Github-Stuff" fallen.

Wäre für eine englische README.md und einen englischen Changelog, aber den Ordner "Github-Stuff" würde ich lieber Deutsch lassen, da es sich hier quasi nur um eine Kommunikation handelt und nicht etwas dokumentiert wird.

**Comment by harrydehix** [comment]
Hier die Ausarbeitung meines Vorschlags.
---
# Konventionen

## Sprache

Die Sprache für die _Dokumentation des Projekts_ (Wiki, Source-Code, Changelog, README.md) ist **Englisch**.

Die Sprache für die _Kommunikation_ (Issues, Kommentare, Protokolle, Tutorials, Nützliche Links) ist **Deutsch**.

Dateien und Ordner sollten immer in **Englisch** benannt werden.

## Lower camel case

Variablen, Dateien, Funktionen und Methoden sollten nach dem _Lower Camel Case_ Schema benannt werden.

#### Beispiele

```markdown
int thisIsAVariable;
iAmAFile.java
public void methodName()
Object helloObject02 = new Object();
```

## Upper camel case

Java-Klassen sollten dagegen dem _Upper Camel Case_ Schema folgen.

#### Beispiele

```markdown
public class MeineKlasse{
 (...)
}
MeineKlasse objektName = new MeineKlasse();
```

**Comment by harrydehix** [comment]
Im zweiten Meeting gelöst.
