### ISSUE TITLE
Organisations Name und Logo

### ISSUE THREAD

**Issue by MrTK-Dev** [STAMACODING/RSA-App#9]
# Name

Ich wäre dafür, dass wir für einen vernünftigen Namen brainstormen, mit dem wir uns alle identifizieren können.
Vorschläge sind **gerne** gesehen!

# Logo

Sobald ein passender Name gefunden wurde, könnte man sich an ein *schönes* Logo setzen.

**Comment by harrydehix** [comment]
Ich glaube, das ist auch nicht mehr relevant.
